sudo: false
language: node_js
node_js:
  - 14
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run build
after_success: npm run coverage
